controller_manager:
  ros__parameters:
    update_rate: 25
    use_sim_time: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    base_controller:
      type: diff_drive_controller/DiffDriveController

    minibot_io_controller:
      type: minibot_controllers/GPIOController

base_controller:
  ros__parameters:
    left_wheel_names: ["l_wheel_joint"]
    right_wheel_names: ["r_wheel_joint"]
    write_op_modes: ["motor_controller"]

    wheel_separation: 0.190 #TBD
    wheels_per_side: 1
    wheel_radius: 0.034 #TBD

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    position_feedback: true
    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    velocity_rolling_window_size: 10
    use_stamped_vel: false

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.25
    linear.x.min_velocity: -0.25
    linear.x.max_acceleration: 0.8
    linear.x.min_acceleration: -0.8
    # linear.x.max_jerk: 0.0
    # linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.5
    angular.z.min_velocity: -1.5
    angular.z.max_acceleration: 1.8
    angular.z.min_acceleration: -1.8
    # angular.z.max_jerk: 0.0
    # angular.z.min_jerk: 0.0